### ISSUE TITLE
Slow process

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#62]
After compound importation we have this process running for a long time.

What is it ? Could this be improved ?

```
			"secs_running" : NumberLong(560),
			"microsecs_running" : NumberLong(560825901),
			"op" : "query",
			"ns" : "pubchem.compounds",
			"command" : {
				"find" : "compounds",
				"filter" : {
					"_seq" : {
						"$lte" : 133360333
					}
				},
				"sort" : {
					"_seq" : -1
				},
				"limit" : 1,
				"lsid" : {
					"id" : UUID("493af11e-fac9-40a8-98a0-3610894fcf69")
				},
				"$db" : "pubchem"
			},
			"planSummary" : "COLLSCAN",
```

**Comment by RicardoSilvestr** [comment]
This process should be due to the "lastDocumentImported" function:
https://github.com/cheminfo/docker-pubchem/blob/3786367e238c91e3f19c54527d336698ac469124/pubchem/src/plugins/compounds/sync/utils/getFilesToImport.js#L20-L24 

I couldn't find why the process is calling it, unless the "incrementalCompoundsImport" function is been call.
Plus we should correct this function, since we have the last _seq number it would be much more faster to search for this number because right now we are getting all documents lower-than/equal to the last _seq number and only after we sort it and get the last one document imported.
I will correct it.
